apiVersion: v1.0
kind: Pod
metadata:
  name: web
  label:
    app: nginx_app
spec:
  containers:
  - name: nginx
    image: web_img
    ports:
      - containerPort: 80

# za spoljasnji pristup treba dodati Servis i Ingress komponentu